[project]
name = "temp-alembic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.1",
    "click>=8.1.8",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.39",
]
